#!/bin/bash

DB_FILENAME="sensorlogs.db"

SQL_DROP_TABLE="DROP TABLE SENSORLOGS;"
SQL_VACUUM="VACUUM;"

SQL_CREATE_TABLE="CREATE TABLE SENSORLOGS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ORIGINATOR_ID TEXT,
  DEVICE_MODEL TEXT,
  TELEGRAM_TYPE TEXT,
  DB_0 TEXT,
  DB_1 TEXT,
  DB_2 TEXT,
  DB_3 TEXT,
  DBM INTEGER,
  TEMPERATURE INTEGER,
  SOIL_MOISTURE INTEGER,
  HUMIDITY INTEGER,
  CONTACT_SWITCH TEXT,
  ROCKER_SWITCH TEXT,
  CREATE_AT TIMESTAMP DEFAULT (DATETIME('now','localtime'))
);"

SQL_SCHEMA=".schema"

echo $SQL_DROP_TABLE | sqlite3 $DB_FILENAME

echo $SQL_VACUUM | sqlite3 $DB_FILENAME

echo $SQL_CREATE_TABLE | sqlite3 $DB_FILENAME

echo $SQL_SCHEMA | sqlite3 $DB_FILENAME

exit 0
